### ISSUE TITLE
AGHTUNG! Arrow Keys 0x80-0x83 is not working!

### ISSUE THREAD

**Issue by DankRank** [HerobrinesArmy/DevCPU#16]
It not works for me. Other keys work.

**Comment by HerobrinesArmy** [comment]
There are a lot of things wrong with the keyboard. It is Notch's keyboard implementation (his source code) and has a lot of specification compliance issues. I've been planning to go through his mapping and get it compliant with the specification. I guess I'll pull that task into Release 0 Update 0. Thanks for the report!

**Comment by HerobrinesArmy** [comment]
I rewrote the key mapping from scratch. I've noticed that a lot of people use the uppercase character codes for key press/release. Notch uses the lowercase character codes, but the specification doesn't say which to use. I've made it optional (not yet configurable from the interface) which one it uses. Right now it uses uppercase, but I'll probably switch it back to lowercase later, to keep people on their toes, and to get back in line with how Notch does it. The specification doesn't require the manufacturer to use a specific case for those, so some manufacturers of the generic hardware might do it one way, and some might do it the other. Software should be written to work in either situation, since it cannot know which way that particular piece of compatible hardware will do it.
