### ISSUE TITLE
Request for advanced macro support

### ISSUE THREAD

**Issue by JeremyWildsmith** [HerobrinesArmy/DevCPU#21]
I would like to request a feature, specifically support for macros.

However, macros implemented as per (or similar to) the support provided by the x86 flat assembler: http://flatassembler.net/docs.php?article=ufasm (look under Macroinstructions)

This would allow powerful code-constructs such as for loops and neater function invoking, i.e:

_invokecdecl pFunction, arg1, arg2, arg3

**Comment by HerobrinesArmy** [comment]
I intend to get macro support added before Release 1. I won't rule out those advanced macro features, but they won't be in Release 1. I'll be reevaluating a lot after Release 1, so we'll see how those advanced macros fit in to the plans moving forward at that time.

My present intention for macro support at Release 1 is:
Defined as so:
.macro MACRO_NAME(FIRST_PARAMETER_NAME,SECOND_PARAMETER_NAME,etc)
.fill 10 SECOND_PARAMETER_NAME
set a FIRST_PARAMETER_NAME
dat "other meaningless instructions and things"
.endmacro

used as so:
MACRO_NAME(whatever, 0x0)

I'm still debating where in the assembly process the handling for macros will occur. I think I need to move away from this "insist on doing everything possible in a single pass" mentality, and allow for more discrete phases in some of the preprocessing activities (since the time added to iterate again over the set of lines isn't going to be noticeable). I don't know; we'll see.

**Comment by JeremyWildsmith** [comment]
Alright sounds good. What you intend on implementing for Release 1 should be perfectly sufficient while I wait for more advanced features.

**Comment by HerobrinesArmy** [comment]
Multiline macro support has been added.
Both:
`#macro somefunc(a, b, c) {
code
code
}`
And:
`.macro somefunc (a,b) ;comments are fine, too
code
code
.endmacro`
are supported.
