### ISSUE TITLE
LWJGL Mac OS X binaries incompatible with Java 7.

### ISSUE THREAD

**Issue by sordgren** [HerobrinesArmy/DevCPU#22]
LWJGL currently does not support Java 7 on Mac OS X with the binaries supplied in the 2.8.5 distribution. Compatible compiled binaries, along with general information about the problem, can be found towards the end of this thread http://lwjgl.org/forum/index.php/topic,4711.0.html. It would be great if these binaries were used on Mac systems that run Java 7 and the binaries supplied in the official distribution used on Mac systems that run earlier versions of Java, as LWJGL (most certainly) crashes the application when loaded into memory using these incompatible binaries.

**Comment by HerobrinesArmy** [comment]
Still? D:
Get your shit straight, Apple....or Sun....or whoever....

**Comment by HerobrinesArmy** [comment]
Well, the latest build, that I published a few days ago, had the last successful nightly build of LWJGL in it, which is what this issue was proposing. I don't know if that fixes the issue, but that's all I can do, so I'm closing this to get it out of my queue. I'll try to keep LWJGL updated to the newest build whenever I publish new versions of DevCPU.
