### ISSUE TITLE
Dropping support for certain (redundant) versions of DevCPU in order to reduce testing and support load in preparation for Release 1

### ISSUE THREAD

**Issue by dilbertfan** [HerobrinesArmy/DevCPU#3]
Due to its complete redundancy, it might make sense to remove the Carbon X86 version of DevCPU.

**Comment by HerobrinesArmy** [comment]
I don't see how it is redundant. Some people prefer Carbon because they're used to it. With every version of DevCPU, some (most, really) platform versions will be untested. I'll be reliant on bug reports in Issues to fix any old or new issues with specific platforms, I wouldn't be inclined to remove one unless it became clear that that platform never worked and wasn't ever going to work. The point of saying that is that it isn't likely to have a significant support load, particularly if no one is using it.

Why do you think it's redundant?

**Comment by dilbertfan** [comment]
Because not a single model of mac has ever had support for Carbon x86 but not Cocoa x86 (AFAIK)

**Comment by HerobrinesArmy** [comment]
That's kind of like saying your computer can support Windows, so why have Mac and Linux versions of DevCPU. I don't imagine that it's a matter of people being unable to use Cocoa; just that they prefer Carbon.

**Comment by dilbertfan** [comment]
Why would you prefer Carbon? It's an API, not something like an interface.

**Comment by HerobrinesArmy** [comment]
I have no idea. I'm literally repeating what someone in the office who uses Mac said to me yesterday. I don't know anything about them. I was led to believe they would be visually distinctive from one another.

**Comment by dilbertfan** [comment]
nope.png
Carbon is a deprecated API that's used by lazyass developers to produce 32 bit only code that's unable to call any API created later then 2007/8. The only good reason why it still exists is because ms is too lazy to port office.

**Comment by ghost** [comment]
The carbon version also does not launch where the cocoa version does.

**Comment by HerobrinesArmy** [comment]
Well, I suppose I can drop Carbon then. Should I drop x86 and PPC Carbon?

**Comment by dilbertfan** [comment]
Seems like a good idea, though I haven't tested PPC Carbon yet to see if it works

**Comment by HerobrinesArmy** [comment]
Test it! =D

**Comment by HerobrinesArmy** [comment]
I've dropped support for all Carbon versions.
