### ISSUE TITLE
Rename Preprocessor Directives

### ISSUE THREAD

**Issue by s-ol** [HerobrinesArmy/DevCPU#38]
I know you plan on adding macros like this:

``.macro xxx( a, b, c )
    set a, b
    add a, c
.endmacro`

but it would be way more useful if you could add "standard" syntax, for compatibilty:

`#macro xxx( a, b, c ) {
  set a, b
  add a, c
}`

I would also change `.include` to `#include` etc.

Last, it would be awesome if you had `#ifdef, #infdef, #else, and #endif.`

Also, maybe change `.reserve` to `reseve` for compatibility too?

**Comment by HerobrinesArmy** [comment]
I'll probably ignore {s and treat } as an alias for .endmacro so that either way works,
All directives work with either '.' or '#'.
Issue #27 covers conditional directives.
I don't want to be compatible with anything that supports naked directives. Anyone wanting to use directives without '.' of '#' in front of them can #define them.

**Comment by HerobrinesArmy** [comment]
I'm leaning toward just supporting Notch-style macros, so:
    #macro somemacro(x,y,z) {
    code
    code
    code
    }
I like that better. I was only ever considering the #macro/#endmacro syntax for compatibility with Organic, but screw Organic.

Oh, also, it is now awesome, because #ifdef, #ifndef, #else, and #endif are fully supported, as is #undef.

#macro is next on my list, so I should be able to close this out soon. :+1:

**Comment by HerobrinesArmy** [comment]
Multiline macro support has been added.

**Comment by s-ol** [comment]
n1!

**Comment by HerobrinesArmy** [comment]
Just a note..
I said "Anyone wanting to use directives without '.' of '#' in front of them can #define them."
With the newly separated preprocessor, that is no longer true for all directives. There is now a distinction between preprocessor directives and assembler directives and it affects what you can do with them. You can't #define preprocessor directives anymore. You can, however, #define assembler directives.
